#!/usr/bin/env python3

# -*- coding: utf-8 -*-
"""UniformRandomNumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tbuMAMz4PdsKMeLPyGc4LBL0aUeMr2aw

UniformRandomNumber.java

/*********************************************************************
 * Book : "Computer Science: An Interdisciplinary Approach" 
 * 
 *
 * Exercise 1.2.30 Uniform random numbers.
 * [EN]  Write a program that prints five uniform random numbers
 *       between 0 and 1, their average value, and their minimum
 *       and maximum values.
 *       Use Math.random(), Math.min(), and Math.max().
 * [RU]  Случайные числа с равномерным распределением. 
 *       Напишите программу, ко­торая выводит пять случайных чисел
 *       с равномерным распределением в диапазоне от 0 до 1, 
 *       их среднее арифметическое, минимальное и максимальное значения.
 *
 * NOTA:  For these two exercises, use only Java features that we have 
 *   introduced in this course so far (e.g,. no loops or conditionals).
 * NOTA:  Esto podemos realizar facil en Python con ayada de numpy
 *********************************************************************/
"""

###  Preparar y ejecutar :D
#
# pyhton3 -m venv ./testUniformRandomNum
# cd ./testUniformRandomNum
# source ./bin/activate
# python3 uniformrandomnumber.py

import numpy as np

s = np.random.uniform(0.00000001,1,5)

print(s)
print(np.max(s), np.min(s), np.average(s))
print(max(s), min(s), sum(s)/5)
